---

- hosts: webservers
  become: yes
  vars:
    jdk: java
  tasks:
    
    - name: java
      debug:
        msg: "{{jdk}}"

    - name: list out ip address
      debug:
        msg: "{{ansible_all_ipv4_addresses}}"


    - name: node name
      debug:
        msg: "{{ansible_nodename}}"
