---

- hosts: centos
  become: yes
  tasks:

    - name: install httpd package
      yum:
        name: httpd
        state: present

    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
 
