---

- hosts: centos
  become: yes
  tasks:

    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
          - git
          - maven
          - unzip
          - python
