---

- hosts: ubuntu
  become: yes
  vars:
    jdk: openjdk-8-jdk
    insta: present

  vars_files:
    - var_file
  tasks:

    - name: install "{{jdk}}"
      apt:
        name: "{{jdk}}"
        state: present

    - name: install "{{pack1}}"
      apt:
        name: "{{pack1}}"
        state: "{{insta}}"
   
    - name: install "{{pack2}}"
      apt:
        name: "{{pack2}}"
        state: "{{insta}}"

    - name: install "{{pack3}}"
      apt:
        name: "{{pack3}}"
        state: "{{insta}}"

    - name: install "{{pack4}}"
      apt:
        name: "{{pack4}}"
        state: "{{insta}}"
